targets:
  $default:
    builders:
      mobx_codegen|mobx_generator:
        enabled: true
        generate_for:
          include:
            - lib/stores/**/*.dart
            - lib/models/**/*.dart