name: tractian_test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

# Scripts are executed using RPS (https://medium.com/@diegokalschne/automatizando-scripts-com-rps-no-dart-e-flutter-91251980b029)
# Activate with: `dart pub global activate rps`
# Run with: `rps mobx`, for example
scripts:
  mobx: "fvm flutter pub run build_runner build --delete-conflicting-outputs"
  build:
    android: "fvm flutter build apk --split-per-abi"
    ios: "fvm flutter build ios"
  clean: "fvm flutter clean"
  get: "fvm flutter pub get"
  run: "fvm flutter run"
  profile: "fvm flutter run --profile"
  install: "fvm flutter install --use-application-binary=D:\\Developer\\Pessoal\\Flutter\\tractian_test\\build\\app\\outputs\\flutter-apk\\app-armeabi-v7a-release.apk"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  flutter_svg: ^2.0.10+1
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  diacritic: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logos/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
